"""Remove rent_per_sqm

Revision ID: 2eb825d9e46e
Revises: a44cac49d669
Create Date: 2022-08-11 11:48:05.675834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2eb825d9e46e'
down_revision = 'a44cac49d669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'rent_per_sqm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('rent_per_sqm', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
