"""make bedrooms nullable

Revision ID: 5ac0163218d8
Revises: d6d8d8d269e4
Create Date: 2022-08-22 18:02:43.626942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ac0163218d8'
down_revision = 'd6d8d8d269e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'units',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'units',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
