"""Initial migration.

Revision ID: a44cac49d669
Revises: 
Create Date: 2022-07-21 18:04:26.589260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44cac49d669'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('is_commercial', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('commercial_type', sa.Enum('converted', 'purpose_built', name='commercialtypes'), nullable=True))
    op.add_column('properties', sa.Column('size_in_sqm', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('rent_per_sqm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'rent_per_sqm')
    op.drop_column('properties', 'size_in_sqm')
    op.drop_column('properties', 'commercial_type')
    op.drop_column('properties', 'is_commercial')
    # ### end Alembic commands ###
