"""make bedrooms nullable

Revision ID: d6d8d8d269e4
Revises: 962848c31228
Create Date: 2022-08-22 17:03:33.617305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd6d8d8d269e4'
down_revision = '962848c31228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'bedrooms',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'bedrooms',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
