"""Added notes

Revision ID: ecee31de24cc
Revises: 5ac0163218d8
Create Date: 2022-08-29 11:36:26.714129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecee31de24cc'
down_revision = '5ac0163218d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'note')
    # ### end Alembic commands ###
